### ISSUE TITLE
Incompatible with the new version of MC

### ISSUE THREAD

**Issue by zfsbsdf** [LiteLDev/PeEditor#10]
When Minecraft is updated to version 1.21.20, I want to open PeEditor and get an error
<img width="576" alt="报错" src="https://github.com/user-attachments/assets/e536331a-24c1-4d3a-ad4c-4ed39d681393">

**Comment by ShrBox** [comment]
Because Mojang has removed .pdb file.

**Comment by zfsbsdf** [comment]
> 因为Mojang已经删除了.pdb文件。

请问有没有什么替代方案

**Comment by ShrBox** [comment]
> > 因为Mojang已经删除了.pdb文件。
> 
> 请问有没有什么替代方案

现在没有，因为Mojang还没有给我们提供必要的调试信息
