### ISSUE TITLE
Missing comma from SkipPerfix array causes unwanted exports.

### ISSUE THREAD

**Issue by crowbarmaster** [LiteLDev/PeEditor#3]
Hello again folks! I spotted a bug today after noticing the executable I built following your formula contained less exports than built with PeEditor. I dumped the PE section and found that exports starting with "?$TSS" were found within the modded executable. After a quick look, I found a comma missing after "?$TSS" within the array. After fixing the comma, building, and running LLPeEditor, the exports directory contains 0x3D99 exports, where it once contained 0x6142 exports.

**Comment by KawaiiNahida** [comment]
fixed in new branch
