### ISSUE TITLE
在执行完LLPeEditor.exe后，将bedrock_server.exe后面加上.BAK

### ISSUE THREAD

**Issue by yqs112358** [LiteLDev/PeEditor#5]
RT，方便用户

**Comment by futrime** [comment]
@yqs112358 你应该在PeEditor仓库提issue

**Comment by yqs112358** [comment]
瞎了，我transfer一下

**Comment by RimuruChan** [comment]
感觉没啥必要，倒不如说可能还有点碍事？（

**Comment by yqs112358** [comment]
很有必要
1. 正常手开偶尔会开错（名字排的有点近）。只有一个exe的话可以一眼开
2. 方便新手理解，减少无意义的询问
3. 装了LL后旧的bedrock_server.exe没有必要再使用，改名是极好的

**Comment by futrime** [comment]
这东西完全可以lip写个脚本解决啊。。。

**Comment by futrime** [comment]
这东西完全可以lip写个脚本解决啊。。。

**Comment by futrime** [comment]
这东西完全可以lip写个脚本解决啊。。。

**Comment by futrime** [comment]
这东西完全可以lip写个脚本解决啊。。。

**Comment by futrime** [comment]
这东西完全可以lip写个脚本解决啊。。。

**Comment by RimuruChan** [comment]
已经写好了

**Comment by futrime** [comment]
gh是不是抽风了，一条评论显示n次。。。
