### ISSUE TITLE
使用PeEditor编辑完后的bedrock_server_mod.exe无法被LLDB附加调试

### ISSUE THREAD

**Issue by yqs112358** [LiteLDev/PeEditor#6]
![image](https://user-images.githubusercontent.com/37969157/225957369-75ce27a8-8107-4014-9a58-4001063dcb9e.png)

原exe不存在此问题，可以正常启动调试
据报告，vscode同样也无法启动调试，目测不是clion附带的lldb的问题

**Comment by RimuruChan** [comment]
手动挂也挂不上，进城会挂

**Comment by RimuruChan** [comment]
Can't fix

**Comment by n15421** [comment]
~~试试就逝世~~
![Image](https://github.com/user-attachments/assets/aa912163-d779-4038-8817-476af4122adb)
