### ISSUE TITLE
缺少所有C函数符号

### ISSUE THREAD

**Issue by cuixiang0130** [LiteLDev/PeEditor#7]
C函数没有name mangling，由于过滤符号时去掉了所有不以?开头的符号，使得导出的lib中没有任何C函数符号。但部分函数是有用的，如quickjs的函数均是extern "C" 的。用例：https://github.com/cuixiang0130/add-module-to-addon

**Comment by RimuruChan** [comment]
不好意思现在才看到，此部分函数请考虑自行通过系统API获取地址，ll生成的头文件本身不含有c函数，生成c函数也会带来不少问题，故而屏蔽
